name: Manual Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the release (e.g., v1.0.0)'
        required: true
        type: string

permissions:
  contents: write # Needed to create releases and upload assets

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.5' # Match go.mod version

      - name: Build multi-arch binaries
        run: make build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: snipcode-binaries-${{ github.run_id }} # Unique name for artifact
          path: dist/ # Upload the entire dist directory

  release:
    name: Create GitHub Release
    needs: build # Run after build job is complete
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: snipcode-binaries-${{ github.run_id }} # Match artifact name from build job
          path: dist/ # Download to a dist directory

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          name: Release ${{ github.event.inputs.tag_name }}
          body: "Release of version ${{ github.event.inputs.tag_name }}"
          draft: false
          prerelease: false
          files: dist/* # Upload all files from the downloaded dist directory
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Provided by GitHub Actions
